version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-nxos-route-target-helper/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-nxos-route-target-helper/actions/workflows/test.yml)

  # Terraform NXOS Route Target helper

  Description
  
  Translates Route Target values from NXOS CLI format to NX-OS DME model format. This module does not create any resources.

  Translation examples:
  ```
  route-target 65535:1      --> "route-target:as2-nn2:65535:1"
  route-target 65536:1      --> "route-target:as4-nn2:65536:1"
  route-target 1.1.1.1:1    --> "route-target:ipv4-nn2:1.1.1.1:1"
  route-target auto         --> "route-target:unknown:0:0"
  ```

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
