version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Route Target Helper

  To run this example you need to execute:

  ```bash
  $ terraform init
  $ terraform plan
  $ terraform apply
  ```

  This example does not create any resources.

  ```hcl
  {{ include "./main.tf" }}
  ```

output:
  file: README.md
  mode: replace
